### ISSUE TITLE
[Linter] Error running OCaml Merlin

### ISSUE THREAD

**Issue by guoyiteng** [314eter/atom-ocaml-merlin#41] opened 2017-08-22 14:27 UTC
When I typed "let" in atom, I got a error from atom
"[Linter] Error running OCaml Merlin 
See Console for more info. (Open View -> Developer -> Toggle Developer Tools)".

After I opened the developer tools, I saw the error below.

[Linter] Error running OCaml Merlin File "src/kernel/mreader_recover.ml", line 169, characters 18-24: Assertion failed
(anonymous) @ /Users/yiteng/.atom/packages/linter/lib/linter-registry.js:159

**Comment by 314eter** [comment] 2017-08-29 12:01
That looks like a bug in Merlin. Is it reproducible?

**Comment by guoyiteng** [comment] 2017-08-29 16:06
Yes, I also reproduce it in another mac.
The os version is macOS sierra 10.12.6.

**Comment by 314eter** [comment] 2017-08-29 16:39
I opened a merlin issue (ocaml/merlin#713), so I'm closing this one.

**Closed as completed by 314eter** 2017-08-29 16:39 UTC
